name: Check and warn if H1 title updated

on:
  pull_request:
    paths:
      - 'src/**/*.md'

jobs:
  check-title:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout base branch
      uses: actions/checkout@v3.5.2
      with:
        ref: ${{ github.base_ref }}
        path: base

    - name: Checkout PR branch
      uses: actions/checkout@v3.5.2
      with:
        ref: ${{ github.head_ref }}
        path: pr

    - name: Get JSON of files changed in PR
      id: files
      uses: actions/github-script@v6.4.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const files = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });
          return JSON.stringify(files.data.filter((file) => file.status !== 'removed').map((file) => file.filename));

    - name: Compare H1 titles of changed files in base branch against PR branch
      run: |
        changed_titles=""
        for file in $(echo "${{ steps.files.outputs.result }}" | jq -r '.[]'); do
          if [[ "$file" == *.md ]]; then
            base_exists=$(test -f base/$file && echo "yes" || echo "no")
            # If the file doesn't exist in the base branch, move to the next file.
            if [[ "$base_exists" == "no" ]]; then
              continue
            fi
            # Extract the H1 title from the article in the base branch.
            base_title=$(git -C base show HEAD:"$file" | awk 'BEGIN {RS="---"} NR>2 {print $0}' | awk -F '#' '/^# / {print $2; exit}')
            # Extract the H1 title from the article in the PR branch.
            pr_title=$(git -C pr show HEAD:"$file" | awk 'BEGIN {RS="---"} NR>2 {print $0}' | awk -F '#' '/^# / {print $2; exit}')
            # If the titles don't match, add file to list of changed titles.
            if [[ "$base_title" != "$pr_title" ]]; then
              changed_titles="$changed_titles, $file"
            fi
          fi
        done

        if [[ ! -z "$changed_titles" ]]; then
          echo "H1 title has changed in the following article(s): ${changed_titles:2}." > comment.txt
          echo "⚠️ If you haven't updated the toc.yml in this branch, be sure to do a ghost commit. Then when you publish, validate the CMS created a redirect URL for each article." >> comment.txt
          echo "See [this Slack thread](https://outsystems.slack.com/archives/C01DGSZ4Y9F/p1686613979251969?thread_ts=1686151875.482399&cid=C01DGSZ4Y9F) for context." >> comment.txt
          echo "changed_titles=true" >> $GITHUB_ENV
        else
          echo "changed_titles=false" >> $GITHUB_ENV
        fi

    - name: Comment on PR if any H1 titles changed
      if: steps.files.outputs.result != '' && env.changed_titles
      uses: actions/github-script@v6.4.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issue_number = context.issue.number;
          const fs = require('fs');
          const commentFile = 'comment.txt';
          if (fs.existsSync(commentFile)) {
            const comment = fs.readFileSync(commentFile, 'utf8');
            if (comment.trim() !== "") {
              github.rest.issues.createComment({
                issue_number: issue_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
          }
